theme = "hugo-theme-console"
baseURL = 'https://bitofbinary.com/'
languageCode = 'en-us'
title = 'Bit of Binary'
pygmentsUseClasses = true
googleAnalytics = "UA-102351311-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  customCSS = ["css/styles.css"]
  syntaxCSS = ["css/syntax.css"]
  [[params.navlinks]]
    name = "About/"
    url = "about/"

  [[params.navlinks]]
    name = "Blog/"
    url = "posts/"

  [[params.navlinks]]
    name = "Books/"
    url = "books/"



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true