theme = "hugo-theme-console"
baseURL = 'https://deekap.com/'
languageCode = 'en-us'
title = 'deekap'
pygmentsUseClasses = true
googleAnalytics = ""
enableEmoji = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  customCSS = ["css/styles.css"]
  syntaxCSS = ["css/syntax.css"]
  [[params.navlinks]]
    name = "About/"
    url = "about/"

  [[params.navlinks]]
    name = "Blog/"
    url = "blog/"

  [[params.navlinks]]
    name = "Bookshelf/"
    url = "books/"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
