# Be sure to change these!
base_url = "https://deekap.com"
title = "{ deekap }"

# generate the feed. This is how it use to be in good old days
generate_feed = true

# Sass compilation is required
compile_sass = true


# Optional: enable tags
taxonomies = [
    {name = "categories"},
    {name = "tags"}
]

render_emoji = true

[slugify]
taxonomies = "on"
anchors = "on"

# Code highlighting
[markdown]
highlight_code = true
# highlight_theme = "boron"
highlight_theme = "base16-ocean-dark"
# highlight_theme = "monokai"

[extra]

# One of: blue, green, orange, pink, red.
# Defaults to blue.
accent_color = "white"

# One of: blue, dark, green, orange, pink, red.
# Enabling dark background will also modify primary font color
# to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "white"

# The logo text - defaults to "Terminimal theme"
logo_text = "{ deekap }"

# The logo link - defaults to base_url.
#logo_home_link = "/take/me/away!"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Deepak"

# Copyright text in HTML format. If specified,
# entirely replaces default copyright and author.
#copyright_html = "My custom&nbsp;<b>copyright</b>"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "home", url = "$BASE_URL"},
    {name = "blog", url = "$BASE_URL/archive"},
    {name = "about", url = "$BASE_URL/about"},
    {name = "bookshelf", url = "$BASE_URL/bookshelf"},
    {name = "photography", url = "$BASE_URL/photography"},

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details

]

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
# favicon = "/favicon.png"
# favicon_mimetype = "image/png"
